# Change from 18 to 20 to satisfy Vite 8 requirements
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm install

RUN chmod -R 755 node_modules/.bin

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
RUN printf 'server { \n\
    listen 8080; \n\
    location / { \n\
        root /usr/share/nginx/html; \n\
        index index.html; \n\
        try_files $uri $uri/ /index.html; \n\
    } \n\
}' > /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]